import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';
import { AuthGuard } from './guard/auth.guard';

const routes: Routes = [
  { path: '', redirectTo: 'landing-page', pathMatch: 'full' },
  { path: 'home',canActivate: [AuthGuard], loadChildren: () => import('./home/home.module').then( m => m.HomePageModule)},
  { path: 'landing-page', loadChildren: './landing-page/landing-page.module#LandingPagePageModule' },
  { path: 'signin', loadChildren: './signin/signin.module#SigninPageModule' },
  { path: 'forgotpass', loadChildren: './forgotpass/forgotpass.module#ForgotpassPageModule' },
  { path: 'signup', loadChildren: './signup/signup.module#SignupPageModule' },
  { path: 'new-claim',canActivate: [AuthGuard], loadChildren: './new-claim/new-claim.module#NewClaimPageModule' },
  { path: 'other', canActivate: [AuthGuard],loadChildren: './other/other.module#OtherPageModule' },
  { path: 'step1', canActivate: [AuthGuard], loadChildren: './other/step1/step1.module#Step1PageModule' },
  { path: 'step2', canActivate: [AuthGuard], loadChildren: './other/step2/step2.module#Step2PageModule' },
  { path: 'step3', canActivate: [AuthGuard], loadChildren: './other/step3/step3.module#Step3PageModule' },
  { path: 'step4',  canActivate: [AuthGuard],loadChildren: './other/step4/step4.module#Step4PageModule' },
  { path: 'review-other',canActivate: [AuthGuard], loadChildren: './other/review-other/review-other.module#ReviewOtherPageModule' },
  { path: 'step5',canActivate: [AuthGuard], loadChildren: './other/step5/step5.module#Step5PageModule' },
  { path: 'general-liability',canActivate: [AuthGuard], loadChildren: './general-liability/general-liability.module#GeneralLiabilityPageModule' },
  { path: 'general-step1',canActivate: [AuthGuard], loadChildren: './general-liability/general-step1/general-step1.module#GeneralStep1PageModule' },
  { path: 'general-step2', canActivate: [AuthGuard],loadChildren: './general-liability/general-step2/general-step2.module#GeneralStep2PageModule' },
  { path: 'general-step3',canActivate: [AuthGuard], loadChildren: './general-liability/general-step3/general-step3.module#GeneralStep3PageModule' },
  { path: 'general-step4',canActivate: [AuthGuard], loadChildren: './general-liability/general-step4/general-step4.module#GeneralStep4PageModule' },
  { path: 'general-step5',canActivate: [AuthGuard], loadChildren: './general-liability/general-step5/general-step5.module#GeneralStep5PageModule' },
  { path: 'general-step6',canActivate: [AuthGuard], loadChildren: './general-liability/general-step6/general-step6.module#GeneralStep6PageModule' },
  { path: 'review-general',canActivate: [AuthGuard], loadChildren: './general-liability/review-general/review-general.module#ReviewGeneralPageModule' },
  { path: 'professional-indemnity',canActivate: [AuthGuard], loadChildren: './professional-indemnity/professional-indemnity.module#ProfessionalIndemnityPageModule' },
  { path: 'professional-step1',canActivate: [AuthGuard], loadChildren: './professional-indemnity/professional-step1/professional-step1.module#ProfessionalStep1PageModule' },
  { path: 'professional-step2',canActivate: [AuthGuard], loadChildren: './professional-indemnity/professional-step2/professional-step2.module#ProfessionalStep2PageModule' },
  { path: 'professional-step3',canActivate: [AuthGuard], loadChildren: './professional-indemnity/professional-step3/professional-step3.module#ProfessionalStep3PageModule' },
  { path: 'professional-step4',canActivate: [AuthGuard], loadChildren: './professional-indemnity/professional-step4/professional-step4.module#ProfessionalStep4PageModule' },
  { path: 'professional-step5',canActivate: [AuthGuard], loadChildren: './professional-indemnity/professional-step5/professional-step5.module#ProfessionalStep5PageModule' },
  { path: 'professional-step6',canActivate: [AuthGuard], loadChildren: './professional-indemnity/professional-step6/professional-step6.module#ProfessionalStep6PageModule' },
  { path: 'professional-step7',canActivate: [AuthGuard], loadChildren: './professional-indemnity/professional-step7/professional-step7.module#ProfessionalStep7PageModule' },
  { path: 'professional-step8', canActivate: [AuthGuard],loadChildren: './professional-indemnity/professional-step8/professional-step8.module#ProfessionalStep8PageModule' },
  { path: 'review-professional',canActivate: [AuthGuard], loadChildren: './professional-indemnity/review-professional/review-professional.module#ReviewProfessionalPageModule' },
  { path: 'medical-malpractice',canActivate: [AuthGuard], loadChildren: './medical-malpractice/medical-malpractice.module#MedicalMalpracticePageModule' },
  { path: 'medical-step1',canActivate: [AuthGuard], loadChildren: './medical-malpractice/medical-step1/medical-step1.module#MedicalStep1PageModule' },
  { path: 'medical-step2',canActivate: [AuthGuard], loadChildren: './medical-malpractice/medical-step2/medical-step2.module#MedicalStep2PageModule' },
  { path: 'medical-step3',canActivate: [AuthGuard], loadChildren: './medical-malpractice/medical-step3/medical-step3.module#MedicalStep3PageModule' },
  { path: 'medical-step4',canActivate: [AuthGuard], loadChildren: './medical-malpractice/medical-step4/medical-step4.module#MedicalStep4PageModule' },
  { path: 'medical-step5',canActivate: [AuthGuard], loadChildren: './medical-malpractice/medical-step5/medical-step5.module#MedicalStep5PageModule' },
  { path: 'medical-step6',canActivate: [AuthGuard], loadChildren: './medical-malpractice/medical-step6/medical-step6.module#MedicalStep6PageModule' },
  { path: 'medical-step7',canActivate: [AuthGuard], loadChildren: './medical-malpractice/medical-step7/medical-step7.module#MedicalStep7PageModule' },
  { path: 'medical-step8',canActivate: [AuthGuard], loadChildren: './medical-malpractice/medical-step8/medical-step8.module#MedicalStep8PageModule' },
  { path: 'review-medical',canActivate: [AuthGuard], loadChildren: './medical-malpractice/review-medical/review-medical.module#ReviewMedicalPageModule' },
  { path: 'vehicle',canActivate: [AuthGuard], loadChildren: './vehicle/vehicle.module#VehiclePageModule' },
  { path: 'vehicle-step1',canActivate: [AuthGuard], loadChildren: './vehicle/vehicle-step1/vehicle-step1.module#VehicleStep1PageModule' },
  { path: 'vehicle-step2',canActivate: [AuthGuard], loadChildren: './vehicle/vehicle-step2/vehicle-step2.module#VehicleStep2PageModule' },
  { path: 'vehicle-step3',canActivate: [AuthGuard], loadChildren: './vehicle/vehicle-step3/vehicle-step3.module#VehicleStep3PageModule' },
  { path: 'vehicle-step5',canActivate: [AuthGuard], loadChildren: './vehicle/vehicle-step5/vehicle-step5.module#VehicleStep5PageModule' },
  { path: 'vehicle-step6',canActivate: [AuthGuard], loadChildren: './vehicle/vehicle-step6/vehicle-step6.module#VehicleStep6PageModule' },
  { path: 'vehicle-step7', canActivate: [AuthGuard], loadChildren: './vehicle/vehicle-step7/vehicle-step7.module#VehicleStep7PageModule' },
  { path: 'property', canActivate: [AuthGuard], loadChildren: './property/property.module#PropertyPageModule' },
  { path: 'property-step1', canActivate: [AuthGuard], loadChildren: './property/property-step1/property-step1.module#PropertyStep1PageModule' },
  { path: 'property-step2', canActivate: [AuthGuard], loadChildren: './property/property-step2/property-step2.module#PropertyStep2PageModule' },
  { path: 'property-step3', canActivate: [AuthGuard], loadChildren: './property/property-step3/property-step3.module#PropertyStep3PageModule' },
  { path: 'property-step5', canActivate: [AuthGuard], loadChildren: './property/property-step5/property-step5.module#PropertyStep5PageModule' },
  { path: 'property-step6', canActivate: [AuthGuard], loadChildren: './property/property-step6/property-step6.module#PropertyStep6PageModule' },
  { path: 'property-step7', canActivate: [AuthGuard], loadChildren: './property/property-step7/property-step7.module#PropertyStep7PageModule' },
  { path: 'property-step8', canActivate: [AuthGuard], loadChildren: './property/property-step8/property-step8.module#PropertyStep8PageModule' },
  { path: 'existing-claim', canActivate: [AuthGuard], loadChildren: './existing-claim/existing-claim.module#ExistingClaimPageModule' },
  { path: 'my-claim', canActivate: [AuthGuard], loadChildren: './my-claim/my-claim.module#MyClaimPageModule' },
  { path: 'my-profile', canActivate: [AuthGuard], loadChildren: './my-profile/my-profile.module#MyProfilePageModule' },
  { path: 'changepass', canActivate: [AuthGuard], loadChildren: './changepass/changepass.module#ChangepassPageModule' },
  { path: 'contactus', canActivate: [AuthGuard], loadChildren: './contactus/contactus.module#ContactusPageModule' },
  { path: 'general-step7', loadChildren: './general-liability/general-step7/general-step7.module#GeneralStep7PageModule' },
  { path: 'professional-step9', loadChildren: './professional-indemnity/professional-step9/professional-step9.module#ProfessionalStep9PageModule' },
  { path: 'medical-step9', loadChildren: './medical-malpractice/medical-step9/medical-step9.module#MedicalStep9PageModule' },
  { path: 'vehicle-step8', loadChildren: './vehicle/vehicle-step8/vehicle-step8.module#VehicleStep8PageModule' },
  { path: 'vehicle-step9', loadChildren: './vehicle/vehicle-step9/vehicle-step9.module#VehicleStep9PageModule' },
  { path: 'review-vehicle', loadChildren: './vehicle/review-vehicle/review-vehicle.module#ReviewVehiclePageModule' },
  { path: 'property-step9', loadChildren: './property/property-step9/property-step9.module#PropertyStep9PageModule' },
  { path: 'review-property', loadChildren: './property/review-property/review-property.module#ReviewPropertyPageModule' },
  { path: 'property-step10', loadChildren: './property/property-step10/property-step10.module#PropertyStep10PageModule' },
  { path: 'windscreen-glass', loadChildren: './vehicle/vehicle-step3/windscreen-glass/windscreen-glass.module#WindscreenGlassPageModule' },
  { path: 'fire', loadChildren: './vehicle/vehicle-step3/fire/fire.module#FirePageModule' },
  { path: 'whether', loadChildren: './vehicle/vehicle-step3/whether/whether.module#WhetherPageModule' },
  { path: 'theft', loadChildren: './vehicle/vehicle-step3/theft/theft.module#TheftPageModule' },
  { path: 'impact', loadChildren: './vehicle/vehicle-step3/impact/impact.module#ImpactPageModule' },
  { path: 'collision', loadChildren: './vehicle/vehicle-step3/collision/collision.module#CollisionPageModule' },
  { path: 'accidental-damage', loadChildren: './property/property-step3/accidental-damage/accidental-damage.module#AccidentalDamagePageModule' },
  { path: 'crime-malicious-damage', loadChildren: './property/property-step3/crime-malicious-damage/crime-malicious-damage.module#CrimeMaliciousDamagePageModule' },
  { path: 'earthquake', loadChildren: './property/property-step3/earthquake/earthquake.module#EarthquakePageModule' },
  { path: 'fire-explosion', loadChildren: './property/property-step3/fire-explosion/fire-explosion.module#FireExplosionPageModule' },
  { path: 'impact-by-collision', loadChildren: './property/property-step3/impact-by-collision/impact-by-collision.module#ImpactByCollisionPageModule' },
  { path: 'impact-by-tree', loadChildren: './property/property-step3/impact-by-tree/impact-by-tree.module#ImpactByTreePageModule' },
  { path: 'escape-of-liquid', loadChildren: './property/property-step3/escape-of-liquid/escape-of-liquid.module#EscapeOfLiquidPageModule' },
  { path: 'weather-related', loadChildren: './property/property-step3/weather-related/weather-related.module#WeatherRelatedPageModule' },
  { path: 'other-damage', loadChildren: './property/property-step3/other-damage/other-damage.module#OtherDamagePageModule' },





];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
